export default {
	ACCOUNT_LOGIN_REQUEST: "ACCOUNT_LOGIN_REQUEST",
	ACCOUNT_LOGIN_SUCCESS: "ACCOUNT_LOGIN_SUCCESS",
	ACCOUNT_LOGIN_FAILED: "ACCOUNT_LOGIN_FAILED",

	ACCOUNT_LOGOUT_REQUEST: "ACCOUNT_LOGOUT_REQUEST",
	ACCOUNT_LOGOUT_SUCCESS: "ACCOUNT_LOGOUT_SUCCESS",
	ACCOUNT_LOGOUT_FAILED: "ACCOUNT_LOGOUT_FAILED",

	ACCOUNT_FORGOT_PASSWORD_REQUEST: "ACCOUNT_FORGOT_PASSWORD_REQUEST",
	ACCOUNT_FORGOT_PASSWORD_SUCCESS: "ACCOUNT_FORGOT_PASSWORD_SUCCESS",
	ACCOUNT_FORGOT_PASSWORD_FAILED: "ACCOUNT_FORGOT_PASSWORD_FAILED",

	ACCOUNT_RESET_PASSWORD_REQUEST: "ACCOUNT_RESET_PASSWORD_REQUEST",
	ACCOUNT_RESET_PASSWORD_SUCCESS: "ACCOUNT_RESET_PASSWORD_SUCCESS",
	ACCOUNT_RESET_PASSWORD_FAILED: "ACCOUNT_RESET_PASSWORD_FAILED",

	GET_ACCOUNTS_REQUEST: "GET_ACCOUNTS_REQUEST",
	GET_ACCOUNTS_SUCCESS: "GET_ACCOUNTS_SUCCESS",
	GET_ACCOUNTS_FAILED: "GET_ACCOUNTS_FAILED",

	GET_CURRENT_ACCOUNT_REQUEST: "GET_CURRENT_ACCOUNT_REQUEST",
	GET_CURRENT_ACCOUNT_SUCCESS: "GET_CURRENT_ACCOUNT_SUCCESS",
	GET_CURRENT_ACCOUNT_FAILED: "GET_CURRENT_ACCOUNT_FAILED",

	GET_ACCOUNT_BY_ID_REQUEST: "GET_ACCOUNT_BY_ID_REQUEST",
	GET_ACCOUNT_BY_ID_SUCCESS: "GET_ACCOUNT_BY_ID_SUCCESS",
	GET_ACCOUNT_BY_ID_FAILED: "GET_ACCOUNT_BY_ID_FAILED",

	CREATE_ACCOUNT_REQUEST: "CREATE_ACCOUNT_REQUEST",
	CREATE_ACCOUNT_SUCCESS: "CREATE_ACCOUNT_SUCCESS",
	CREATE_ACCOUNT_FAILED: "CREATE_ACCOUNT_FAILED",

	UPDATE_ACCOUNT_REQUEST: "UPDATE_ACCOUNT_REQUEST",
	UPDATE_ACCOUNT_SUCCESS: "UPDATE_ACCOUNT_SUCCESS",
	UPDATE_ACCOUNT_FAILED: "UPDATE_ACCOUNT_FAILED",

	DELETE_ACCOUNT_REQUEST: "DELETE_ACCOUNT_REQUEST",
	DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
	DELETE_ACCOUNT_FAILED: "DELETE_ACCOUNT_FAILED",

	CONFIG_PASSWORD_ACCOUNT_REQUEST: "CONFIG_PASSWORD_ACCOUNT_REQUEST",
	CONFIG_PASSWORD_ACCOUNT_SUCCESS: "CONFIG_PASSWORD_ACCOUNT_SUCCESS",
	CONFIG_PASSWORD_ACCOUNT_FAILED: "CONFIG_PASSWORD_ACCOUNT_FAILED",

	ACCOUNT_CHANGE_PASSWORD_REQUEST: "ACCOUNT_CHANGE_PASSWORD_REQUEST",
	ACCOUNT_CHANGE_PASSWORD_SUCCESS: "ACCOUNT_CHANGE_PASSWORD_SUCCESS",
	ACCOUNT_CHANGE_PASSWORD_FAILED: "ACCOUNT_CHANGE_PASSWORD_FAILED",

	GET_ROLES_REQUEST: "GET_ROLES_REQUEST",
	GET_ROLES_SUCCESS: "GET_ROLES_SUCCESS",
	GET_ROLES_FAILED: "GET_ROLES_FAILED",

	GET_ROLE_BY_ID_REQUEST: "GET_ROLE_BY_ID_REQUEST",
	GET_ROLE_BY_ID_SUCCESS: "GET_ROLE_BY_ID_SUCCESS",
	GET_ROLE_BY_ID_FAILED: "GET_ROLE_BY_ID_FAILED",

	GET_ROLE_PERMISSION_REQUEST: "GET_ROLE_PERMISSION_REQUEST",
	GET_ROLE_PERMISSION_SUCCESS: "GET_ROLE_PERMISSION_SUCCESS",
	GET_ROLE_PERMISSION_FAILED: "GET_ROLE_PERMISSION_FAILED",

	CREATE_ROLE_REQUEST: "CREATE_ROLE_REQUEST",
	CREATE_ROLE_SUCCESS: "CREATE_ROLE_SUCCESS",
	CREATE_ROLE_FAILED: "CREATE_ROLE_FAILED",

	UPDATE_ROLE_REQUEST: "UPDATE_ROLE_REQUEST",
	UPDATE_ROLE_SUCCESS: "UPDATE_ROLE_SUCCESS",
	UPDATE_ROLE_FAILED: "UPDATE_ROLE_FAILED",

	DELETE_ROLE_REQUEST: "DELETE_ROLE_REQUEST",
	DELETE_ROLE_SUCCESS: "DELETE_ROLE_SUCCESS",
	DELETE_ROLE_FAILED: "DELETE_ROLE_FAILED",

	GET_CUSTOMERS_REQUEST: "GET_CUSTOMERS_REQUEST",
	GET_CUSTOMERS_SUCCESS: "GET_CUSTOMERS_SUCCESS",
	GET_CUSTOMERS_FAILED: "GET_CUSTOMERS_FAILED",

	GET_CUSTOMER_BY_ID_REQUEST: "GET_CUSTOMER_BY_ID_REQUEST",
	GET_CUSTOMER_BY_ID_SUCCESS: "GET_CUSTOMER_BY_ID_SUCCESS",
	GET_CUSTOMER_BY_ID_FAILED: "GET_CUSTOMER_BY_ID_FAILED",

	CREATE_CUSTOMER_REQUEST: "CREATE_CUSTOMER_REQUEST",
	CREATE_CUSTOMER_SUCCESS: "CREATE_CUSTOMER_SUCCESS",
	CREATE_CUSTOMER_FAILED: "CREATE_CUSTOMER_FAILED",

	UPDATE_CUSTOMER_REQUEST: "UPDATE_CUSTOMER_REQUEST",
	UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",
	UPDATE_CUSTOMER_FAILED: "UPDATE_CUSTOMER_FAILED",

	DELETE_CUSTOMER_REQUEST: "DELETE_CUSTOMER_REQUEST",
	DELETE_CUSTOMER_SUCCESS: "DELETE_CUSTOMER_SUCCESS",
	DELETE_CUSTOMER_FAILED: "DELETE_CUSTOMER_FAILED",

	GET_PRODUCERS_REQUEST: "GET_PRODUCERS_REQUEST",
	GET_PRODUCERS_SUCCESS: "GET_PRODUCERS_SUCCESS",
	GET_PRODUCERS_FAILED: "GET_PRODUCERS_FAILED",

	GET_PRODUCER_BY_ID_REQUEST: "GET_PRODUCER_BY_ID_REQUEST",
	GET_PRODUCER_BY_ID_SUCCESS: "GET_PRODUCER_BY_ID_SUCCESS",
	GET_PRODUCER_BY_ID_FAILED: "GET_PRODUCER_BY_ID_FAILED",

	CREATE_PRODUCER_REQUEST: "CREATE_PRODUCER_REQUEST",
	CREATE_PRODUCER_SUCCESS: "CREATE_PRODUCER_SUCCESS",
	CREATE_PRODUCER_FAILED: "CREATE_PRODUCER_FAILED",

	UPDATE_PRODUCER_REQUEST: "UPDATE_PRODUCER_REQUEST",
	UPDATE_PRODUCER_SUCCESS: "UPDATE_PRODUCER_SUCCESS",
	UPDATE_PRODUCER_FAILED: "UPDATE_PRODUCER_FAILED",

	DELETE_PRODUCER_REQUEST: "DELETE_PRODUCER_REQUEST",
	DELETE_PRODUCER_SUCCESS: "DELETE_PRODUCER_SUCCESS",
	DELETE_PRODUCER_FAILED: "DELETE_PRODUCER_FAILED",

	GET_NPLS_REQUEST: "GET_NPLS_REQUEST",
	GET_NPLS_SUCCESS: "GET_NPLS_SUCCESS",
	GET_NPLS_FAILED: "GET_NPLS_FAILED",

	GET_NPL_BY_ID_REQUEST: "GET_NPL_BY_ID_REQUEST",
	GET_NPL_BY_ID_SUCCESS: "GET_NPL_BY_ID_SUCCESS",
	GET_NPL_BY_ID_FAILED: "GET_NPL_BY_ID_FAILED",

	CREATE_NPL_REQUEST: "CREATE_NPL_REQUEST",
	CREATE_NPL_SUCCESS: "CREATE_NPL_SUCCESS",
	CREATE_NPL_FAILED: "CREATE_NPL_FAILED",

	UPDATE_NPL_REQUEST: "UPDATE_NPL_REQUEST",
	UPDATE_NPL_SUCCESS: "UPDATE_NPL_SUCCESS",
	UPDATE_NPL_FAILED: "UPDATE_NPL_FAILED",

	DELETE_NPL_REQUEST: "DELETE_NPL_REQUEST",
	DELETE_NPL_SUCCESS: "DELETE_NPL_SUCCESS",
	DELETE_NPL_FAILED: "DELETE_NPL_FAILED",

	GET_NPL_GROUPS_REQUEST: "GET_NPL_GROUPS_REQUEST",
	GET_NPL_GROUPS_SUCCESS: "GET_NPL_GROUPS_SUCCESS",
	GET_NPL_GROUPS_FAILED: "GET_NPL_GROUPS_FAILED",

	GET_NPL_GROUP_BY_ID_REQUEST: "GET_NPL_GROUP_BY_ID_REQUEST",
	GET_NPL_GROUP_BY_ID_SUCCESS: "GET_NPL_GROUP_BY_ID_SUCCESS",
	GET_NPL_GROUP_BY_ID_FAILED: "GET_NPL_GROUP_BY_ID_FAILED",

	CREATE_NPL_GROUP_REQUEST: "CREATE_NPL_GROUP_REQUEST",
	CREATE_NPL_GROUP_SUCCESS: "CREATE_NPL_GROUP_SUCCESS",
	CREATE_NPL_GROUP_FAILED: "CREATE_NPL_GROUP_FAILED",

	UPDATE_NPL_GROUP_REQUEST: "UPDATE_NPL_GROUP_REQUEST",
	UPDATE_NPL_GROUP_SUCCESS: "UPDATE_NPL_GROUP_SUCCESS",
	UPDATE_NPL_GROUP_FAILED: "UPDATE_NPL_GROUP_FAILED",

	DELETE_NPL_GROUP_REQUEST: "DELETE_NPL_GROUP_REQUEST",
	DELETE_NPL_GROUP_SUCCESS: "DELETE_NPL_GROUP_SUCCESS",
	DELETE_NPL_GROUP_FAILED: "DELETE_NPL_GROUP_FAILED",

	GET_ORDERS_REQUEST: "GET_ORDERS_REQUEST",
	GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
	GET_ORDERS_FAILED: "GET_ORDERS_FAILED",

	GET_ORDER_BY_ID_REQUEST: "GET_ORDER_BY_ID_REQUEST",
	GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",
	GET_ORDER_BY_ID_FAILED: "GET_ORDER_BY_ID_FAILED",

	CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
	CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
	CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED",

	UPDATE_ORDER_REQUEST: "UPDATE_ORDER_REQUEST",
	UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
	UPDATE_ORDER_FAILED: "UPDATE_ORDER_FAILED",

	DELETE_ORDER_REQUEST: "DELETE_ORDER_REQUEST",
	DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
	DELETE_ORDER_FAILED: "DELETE_ORDER_FAILED",

	APPROVE_ORDER_REQUEST: "APPROVE_ORDER_REQUEST",
	APPROVE_ORDER_SUCCESS: "APPROVE_ORDER_SUCCESS",
	APPROVE_ORDER_FAILED: "APPROVE_ORDER_FAILED",

	GET_CUSTOMERS_IN_ORDER_REQUEST: "GET_CUSTOMERS_IN_ORDER_REQUEST",
	GET_CUSTOMERS_IN_ORDER_SUCCESS: "GET_CUSTOMERS_IN_ORDER_SUCCESS",
	GET_CUSTOMERS_IN_ORDER_FAILED: "GET_CUSTOMERS_IN_ORDER_FAILED",

	GET_CUSTOMER_IN_ORDER_REQUEST: "GET_CUSTOMER_IN_ORDER_REQUEST",
	GET_CUSTOMER_IN_ORDER_SUCCESS: "GET_CUSTOMER_IN_ORDER_SUCCESS",
	GET_CUSTOMER_IN_ORDER_FAILED: "GET_CUSTOMER_IN_ORDER_FAILED",

	GET_CUSTOMER_IN_ORDER_REQUEST: "GET_CUSTOMER_IN_ORDER_REQUEST",
	GET_CUSTOMER_IN_ORDER_SUCCESS: "GET_CUSTOMER_IN_ORDER_SUCCESS",
	GET_CUSTOMER_IN_ORDER_FAILED: "GET_CUSTOMER_IN_ORDER_FAILED",

	UPLOAD_CUSTOMER_ORDER_REQUEST: "UPLOAD_CUSTOMER_ORDER_REQUEST",
	UPLOAD_CUSTOMER_ORDER_SUCCESS: "UPLOAD_CUSTOMER_ORDER_SUCCESS",
	UPLOAD_CUSTOMER_ORDER_FAILED: "UPLOAD_CUSTOMER_ORDER_FAILED",

	CREATE_PRODUCT_TYPE_REQUEST: "CREATE_PRODUCT_TYPE_REQUEST",
	CREATE_PRODUCT_TYPE_SUCCESS: "CREATE_PRODUCT_TYPE_SUCCESS",
	CREATE_PRODUCT_TYPE_FAILED: "CREATE_PRODUCT_TYPE_FAILED",

	UPDATE_PRODUCT_TYPE_REQUEST: "UPDATE_PRODUCT_TYPE_REQUEST",
	UPDATE_PRODUCT_TYPE_SUCCESS: "UPDATE_PRODUCT_TYPE_SUCCESS",
	UPDATE_PRODUCT_TYPE_FAILED: "UPDATE_PRODUCT_TYPE_FAILED",

	DELETE_PRODUCT_TYPE_REQUEST: "DELETE_PRODUCT_TYPE_REQUEST",
	DELETE_PRODUCT_TYPE_SUCCESS: "DELETE_PRODUCT_TYPE_SUCCESS",
	DELETE_PRODUCT_TYPE_FAILED: "DELETE_PRODUCT_TYPE_FAILED",

	GET_PRODUCT_TYPES_REQUEST: "GET_PRODUCT_TYPES_REQUEST",
	GET_PRODUCT_TYPES_SUCCESS: "GET_PRODUCT_TYPES_SUCCESS",
	GET_PRODUCT_TYPES_FAILED: "GET_PRODUCT_TYPES_FAILED",

	CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
	CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
	CREATE_PRODUCT_FAILED: "CREATE_PRODUCT_FAILED",

	UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
	UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
	UPDATE_PRODUCT_FAILED: "UPDATE_PRODUCT_FAILED",

	DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
	DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
	DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",

	GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
	GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
	GET_PRODUCTS_FAILED: "GET_PRODUCTS_FAILED",

	GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
	GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
	GET_PRODUCT_BY_ID_FAILED: "GET_PRODUCT_BY_ID_FAILED",

	GET_MEASUREMENT_STANDARDS_REQUEST: "GET_MEASUREMENT_STANDARDS_REQUEST",
	GET_MEASUREMENT_STANDARDS_SUCCESS: "GET_MEASUREMENT_STANDARDS_SUCCESS",
	GET_MEASUREMENT_STANDARDS_FAILED: "GET_MEASUREMENT_STANDARDS_FAILED",

	GET_MEASUREMENT_STANDARD_BY_ID_REQUEST:
		"GET_MEASUREMENT_STANDARD_BY_ID_REQUEST",
	GET_MEASUREMENT_STANDARD_BY_ID_SUCCESS:
		"GET_MEASUREMENT_STANDARD_BY_ID_SUCCESS",
	GET_MEASUREMENT_STANDARD_BY_ID_FAILED:
		"GET_MEASUREMENT_STANDARD_BY_ID_FAILED",

	CREATE_MEASUREMENT_STANDARD_REQUEST: "CREATE_MEASUREMENT_STANDARD_REQUEST",
	CREATE_MEASUREMENT_STANDARD_SUCCESS: "CREATE_MEASUREMENT_STANDARD_SUCCESS",
	CREATE_MEASUREMENT_STANDARD_FAILED: "CREATE_MEASUREMENT_STANDARD_FAILED",

	UPDATE_MEASUREMENT_STANDARD_REQUEST: "UPDATE_MEASUREMENT_STANDARD_REQUEST",
	UPDATE_MEASUREMENT_STANDARD_SUCCESS: "UPDATE_MEASUREMENT_STANDARD_SUCCESS",
	UPDATE_MEASUREMENT_STANDARD_FAILED: "UPDATE_MEASUREMENT_STANDARD_FAILED",

	DELETE_MEASUREMENT_STANDARD_REQUEST: "DELETE_MEASUREMENT_STANDARD_REQUEST",
	DELETE_MEASUREMENT_STANDARD_SUCCESS: "DELETE_MEASUREMENT_STANDARD_SUCCESS",
	DELETE_MEASUREMENT_STANDARD_FAILED: "DELETE_MEASUREMENT_STANDARD_FAILED",

	GET_PRODUCT_PARAMETERS_REQUEST: "GET_PRODUCT_PARAMETERS_REQUEST",
	GET_PRODUCT_PARAMETERS_SUCCESS: "GET_PRODUCT_PARAMETERS_SUCCESS",
	GET_PRODUCT_PARAMETERS_FAILED: "GET_PRODUCT_PARAMETERS_FAILED",

	GET_PROVINCES_REQUEST: "GET_PROVINCES_REQUEST",
	GET_PROVINCES_SUCCESS: "GET_PROVINCES_SUCCESS",
	GET_PROVINCES_FAILED: "GET_PROVINCES_FAILED",

	GET_PROVINCE_BY_ID_REQUEST: "GET_PROVINCE_BY_ID_REQUEST",
	GET_PROVINCE_BY_ID_SUCCESS: "GET_PROVINCE_BY_ID_SUCCESS",
	GET_PROVINCE_BY_ID_FAILED: "GET_PROVINCE_BY_ID_FAILED",

	GET_ORDER_PLANS_REQUEST: "GET_ORDER_PLANS_REQUEST",
	GET_ORDER_PLANS_SUCCESS: "GET_ORDER_PLANS_SUCCESS",
	GET_ORDER_PLANS_FAILED: "GET_ORDER_PLANS_FAILED",

	GET_ORDER_PLAN_BY_ID_REQUEST: "GET_ORDER_PLAN_BY_ID_REQUEST",
	GET_ORDER_PLAN_BY_ID_SUCCESS: "GET_ORDER_PLAN_BY_ID_SUCCESS",
	GET_ORDER_PLAN_BY_ID_FAILED: "GET_ORDER_PLAN_BY_ID_FAILED",

	CREATE_ORDER_PLAN_REQUEST: "CREATE_ORDER_PLAN_REQUEST",
	CREATE_ORDER_PLAN_SUCCESS: "CREATE_ORDER_PLAN_SUCCESS",
	CREATE_ORDER_PLAN_FAILED: "CREATE_ORDER_PLAN_FAILED",

	UPDATE_ORDER_PLAN_REQUEST: "UPDATE_ORDER_PLAN_REQUEST",
	UPDATE_ORDER_PLAN_SUCCESS: "UPDATE_ORDER_PLAN_SUCCESS",
	UPDATE_ORDER_PLAN_FAILED: "UPDATE_ORDER_PLAN_FAILED",

	DELETE_ORDER_PLAN_REQUEST: "DELETE_ORDER_PLAN_REQUEST",
	DELETE_ORDER_PLAN_SUCCESS: "DELETE_ORDER_PLAN_SUCCESS",
	DELETE_ORDER_PLAN_FAILED: "DELETE_ORDER_PLAN_FAILED",

	GET_MEASURE_SIZES_REQUEST: "GET_MEASURE_SIZES_REQUEST",
	GET_MEASURE_SIZES_SUCCESS: "GET_MEASURE_SIZES_SUCCESS",
	GET_MEASURE_SIZES_FAILED: "GET_MEASURE_SIZES_FAILED",

	GET_MEASURE_SIZE_BY_ID_REQUEST: "GET_MEASURE_SIZE_BY_ID_REQUEST",
	GET_MEASURE_SIZE_BY_ID_SUCCESS: "GET_MEASURE_SIZE_BY_ID_SUCCESS",
	GET_MEASURE_SIZE_BY_ID_FAILED: "GET_MEASURE_SIZE_BY_ID_FAILED",

	CREATE_MEASURE_SIZE_REQUEST: "CREATE_MEASURE_SIZE_REQUEST",
	CREATE_MEASURE_SIZE_SUCCESS: "CREATE_MEASURE_SIZE_SUCCESS",
	CREATE_MEASURE_SIZE_FAILED: "CREATE_MEASURE_SIZE_FAILED",

	UPDATE_MEASURE_SIZE_REQUEST: "UPDATE_MEASURE_SIZE_REQUEST",
	UPDATE_MEASURE_SIZE_SUCCESS: "UPDATE_MEASURE_SIZE_SUCCESS",
	UPDATE_MEASURE_SIZE_FAILED: "UPDATE_MEASURE_SIZE_FAILED",

	DELETE_MEASURE_SIZE_REQUEST: "DELETE_MEASURE_SIZE_REQUEST",
	DELETE_MEASURE_SIZE_SUCCESS: "DELETE_MEASURE_SIZE_SUCCESS",
	DELETE_MEASURE_SIZE_FAILED: "DELETE_MEASURE_SIZE_FAILED",

	CONVERT_MEASURE_SIZE_REQUEST: "CONVERT_MEASURE_SIZE_REQUEST",
	CONVERT_MEASURE_SIZE_SUCCESS: "CONVERT_MEASURE_SIZE_SUCCESS",
	CONVERT_MEASURE_SIZE_FAILED: "CONVERT_MEASURE_SIZE_FAILED",

	ADD_SEW_MEASURE_SIZE_REQUEST: "ADD_SEW_MEASURE_SIZE_REQUEST",
	ADD_SEW_MEASURE_SIZE_SUCCESS: "ADD_SEW_MEASURE_SIZE_SUCCESS",
	ADD_SEW_MEASURE_SIZE_FAILED: "ADD_SEW_MEASURE_SIZE_FAILED",

	UPDATE_CUSTOMER_IN_ORDER_REQUEST: "UPDATE_CUSTOMER_IN_ORDER_REQUEST",
	UPDATE_CUSTOMER_IN_ORDER_SUCCESS: "UPDATE_CUSTOMER_IN_ORDER_SUCCESS",
	UPDATE_CUSTOMER_IN_ORDER_FAILED: "UPDATE_CUSTOMER_IN_ORDER_FAILED",

	GET_ORDERS_CONVERT_REQUEST: "GET_ORDERS_CONVERT_REQUEST",
	GET_ORDERS_CONVERT_SUCCESS: "GET_ORDERS_CONVERT_SUCCESS",
	GET_ORDERS_CONVERT_FAILED: "GET_ORDERS_CONVERT_FAILED",

	GET_UNITS_REQUEST: "GET_UNITS_REQUEST",
	GET_UNITS_SUCCESS: "GET_UNITS_SUCCESS",
	GET_UNITS_FAILED: "GET_UNITS_FAILED",

	GET_UNIT_BY_ID_REQUEST: "GET_UNIT_BY_ID_REQUEST",
	GET_UNIT_BY_ID_SUCCESS: "GET_UNIT_BY_ID_SUCCESS",
	GET_UNIT_BY_ID_FAILED: "GET_UNIT_BY_ID_FAILED",

	CREATE_UNIT_REQUEST: "CREATE_UNIT_REQUEST",
	CREATE_UNIT_SUCCESS: "CREATE_UNIT_SUCCESS",
	CREATE_UNIT_FAILED: "CREATE_UNIT_FAILED",

	UPDATE_UNIT_REQUEST: "UPDATE_UNIT_REQUEST",
	UPDATE_UNIT_SUCCESS: "UPDATE_UNIT_SUCCESS",
	UPDATE_UNIT_FAILED: "UPDATE_UNIT_FAILED",

	DELETE_UNIT_REQUEST: "DELETE_UNIT_REQUEST",
	DELETE_UNIT_SUCCESS: "DELETE_UNIT_SUCCESS",
	DELETE_UNIT_FAILED: "DELETE_UNIT_FAILED",

	GET_MATERIAL_NORMS_REQUEST: "GET_MATERIAL_NORMS_REQUEST",
	GET_MATERIAL_NORMS_SUCCESS: "GET_MATERIAL_NORMS_SUCCESS",
	GET_MATERIAL_NORMS_FAILED: "GET_MATERIAL_NORMS_FAILED",

	GET_MATERIAL_NORM_BY_ID_REQUEST: "GET_MATERIAL_NORM_BY_ID_REQUEST",
	GET_MATERIAL_NORM_BY_ID_SUCCESS: "GET_MATERIAL_NORM_BY_ID_SUCCESS",
	GET_MATERIAL_NORM_BY_ID_FAILED: "GET_MATERIAL_NORM_BY_ID_FAILED",

	CREATE_MATERIAL_NORM_REQUEST: "CREATE_MATERIAL_NORM_REQUEST",
	CREATE_MATERIAL_NORM_SUCCESS: "CREATE_MATERIAL_NORM_SUCCESS",
	CREATE_MATERIAL_NORM_FAILED: "CREATE_MATERIAL_NORM_FAILED",

	UPDATE_MATERIAL_NORM_REQUEST: "UPDATE_MATERIAL_NORM_REQUEST",
	UPDATE_MATERIAL_NORM_SUCCESS: "UPDATE_MATERIAL_NORM_SUCCESS",
	UPDATE_MATERIAL_NORM_FAILED: "UPDATE_MATERIAL_NORM_FAILED",

	DELETE_MATERIAL_NORM_REQUEST: "DELETE_MATERIAL_NORM_REQUEST",
	DELETE_MATERIAL_NORM_SUCCESS: "DELETE_MATERIAL_NORM_SUCCESS",
	DELETE_MATERIAL_NORM_FAILED: "DELETE_MATERIAL_NORM_FAILED",

	GET_ALL_PRODUCT_IN_ORDER_REQUEST: "GET_ALL_PRODUCT_IN_ORDER_REQUEST",
	GET_ALL_PRODUCT_IN_ORDER_SUCCESS: "GET_ALL_PRODUCT_IN_ORDER_SUCCESS",
	GET_ALL_PRODUCT_IN_ORDER_FAILED: "GET_ALL_PRODUCT_IN_ORDER_FAILED",

	GET_NPL_ORDERS_REQUEST: "GET_NPL_ORDERS_REQUEST",
	GET_NPL_ORDERS_SUCCESS: "GET_NPL_ORDERS_SUCCESS",
	GET_NPL_ORDERS_FAILED: "GET_NPL_ORDERS_FAILED",

	GET_NPL_ORDER_BY_ID_REQUEST: "GET_NPL_ORDER_BY_ID_REQUEST",
	GET_NPL_ORDER_BY_ID_SUCCESS: "GET_NPL_ORDER_BY_ID_SUCCESS",
	GET_NPL_ORDER_BY_ID_FAILED: "GET_NPL_ORDER_BY_ID_FAILED",

	CREATE_NPL_ORDER_REQUEST: "CREATE_NPL_ORDER_REQUEST",
	CREATE_NPL_ORDER_SUCCESS: "CREATE_NPL_ORDER_SUCCESS",
	CREATE_NPL_ORDER_FAILED: "CREATE_NPL_ORDER_FAILED",

	UPDATE_NPL_ORDER_REQUEST: "UPDATE_NPL_ORDER_REQUEST",
	UPDATE_NPL_ORDER_SUCCESS: "UPDATE_NPL_ORDER_SUCCESS",
	UPDATE_NPL_ORDER_FAILED: "UPDATE_NPL_ORDER_FAILED",

	DELETE_NPL_ORDER_REQUEST: "DELETE_NPL_ORDER_REQUEST",
	DELETE_NPL_ORDER_SUCCESS: "DELETE_NPL_ORDER_SUCCESS",
	DELETE_NPL_ORDER_FAILED: "DELETE_NPL_ORDER_FAILED",

	GET_UNUSUAL_LIST_REQUEST: "GET_UNUSUAL_LIST_REQUEST",
	GET_UNUSUAL_LIST_SUCCESS: "GET_UNUSUAL_LIST_SUCCESS",
	GET_UNUSUAL_LIST_FAILED: "GET_UNUSUAL_LIST_FAILED",

	GET_ALL_PRODUCT_IN_ORDER_REQUEST: "GET_ALL_PRODUCT_IN_ORDER_REQUEST",
	GET_ALL_PRODUCT_IN_ORDER_SUCCESS: "GET_ALL_PRODUCT_IN_ORDER_SUCCESS",
	GET_ALL_PRODUCT_IN_ORDER_FAILED: "GET_ALL_PRODUCT_IN_ORDER_FAILED",

	CHECK_UNUSUAL_SIZE_REQUEST: "CHECK_UNUSUAL_SIZE_REQUEST",
	CHECK_UNUSUAL_SIZE_SUCCESS: "CHECK_UNUSUAL_SIZE_SUCCESS",
	CHECK_UNUSUAL_SIZE_FAILED: "CHECK_UNUSUAL_SIZE_FAILED",

	APPROVE_ALL_CUSTOMER_IN_ORDER_REQUEST:
		"APPROVE_ALL_CUSTOMER_IN_ORDER_REQUEST",
	APPROVE_ALL_CUSTOMER_IN_ORDER_SUCCESS:
		"APPROVE_ALL_CUSTOMER_IN_ORDER_SUCCESS",
	APPROVE_ALL_CUSTOMER_IN_ORDER_FAILED: "APPROVE_ALL_CUSTOMER_IN_ORDER_FAILED",

	APPROVE_MANY_CUSTOMER_IN_ORDER_REQUEST:
		"APPROVE_MANY_CUSTOMER_IN_ORDER_REQUEST",
	APPROVE_MANY_CUSTOMER_IN_ORDER_SUCCESS:
		"APPROVE_MANY_CUSTOMER_IN_ORDER_SUCCESS",
	APPROVE_MANY_CUSTOMER_IN_ORDER_FAILED:
		"APPROVE_MANY_CUSTOMER_IN_ORDER_FAILED",
};
